# Generated by Django 4.1.7 on 2023-03-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_attempts_user_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(blank=True),
        ),
    ]
